export const LANGUAGES = [
    "English",
    "Turkish",
    "German",
    "French",
    "Spanish",
    "Afrikaans",
    "Albanian",
    "Arabic",
    "Armenian",
    "Azerbaijani",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bulgarian",
    "Catalan",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "Estonian",
    "Filipino",
    "Finnish",
    "Galician",
    "Georgian",
    "Greek",
    "Gujarati",
    "Haitian Creole",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Kannada",
    "Korean",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Malay",
    "Maltese",
    "Norwegian",
    "Persian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Swahili",
    "Swedish",
    "Tamil",
    "Telugu",
    "Thai",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Welsh",
    "Yiddish"
];

export const LANGUAGE_CODES: { [key: string]: string } = {
    "English": "En",
    "Turkish": "Tr",
    "German": "De",
    "French": "Fr",
    "Spanish": "Es",
    "Afrikaans": "Af",
    "Albanian": "Sq",
    "Arabic": "Ar",
    "Armenian": "Hy",
    "Azerbaijani": "Az",
    "Basque": "Eu",
    "Belarusian": "Be",
    "Bengali": "Bn",
    "Bulgarian": "Bg",
    "Catalan": "Ca",
    "Chinese": "Zh",
    "Croatian": "Hr",
    "Czech": "Cs",
    "Danish": "Da",
    "Dutch": "Nl",
    "Estonian": "Et",
    "Filipino": "Tl",
    "Finnish": "Fi",
    "Galician": "Gl",
    "Georgian": "Ka",
    "Greek": "El",
    "Gujarati": "Gu",
    "Haitian Creole": "Ht",
    "Hebrew": "He",
    "Hindi": "Hi",
    "Hungarian": "Hu",
    "Icelandic": "Is",
    "Indonesian": "Id",
    "Irish": "Ga",
    "Italian": "It",
    "Japanese": "Ja",
    "Kannada": "Kn",
    "Korean": "Ko",
    "Latin": "La",
    "Latvian": "Lv",
    "Lithuanian": "Lt",
    "Macedonian": "Mk",
    "Malay": "Ms",
    "Maltese": "Mt",
    "Norwegian": "No",
    "Persian": "Fa",
    "Polish": "Pl",
    "Portuguese": "Pt",
    "Romanian": "Ro",
    "Russian": "Ru",
    "Serbian": "Sr",
    "Slovak": "Sk",
    "Slovenian": "Sl",
    "Swahili": "Sw",
    "Swedish": "Sv",
    "Tamil": "Ta",
    "Telugu": "Te",
    "Thai": "Th",
    "Ukrainian": "Uk",
    "Urdu": "Ur",
    "Vietnamese": "Vi",
    "Welsh": "Cy",
    "Yiddish": "Yi"
};
